// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nmfall
List nmfall(arma::mat data, int noSignatures, std::string distribution, std::string method, arma::colvec alpha, double pwr, arma::mat wmat, arma::mat hmat, arma::mat w1mat, arma::mat w2mat, int maxiter, double tolerance, int initial, int smallIter);
RcppExport SEXP _nmfgenr_nmfall(SEXP dataSEXP, SEXP noSignaturesSEXP, SEXP distributionSEXP, SEXP methodSEXP, SEXP alphaSEXP, SEXP pwrSEXP, SEXP wmatSEXP, SEXP hmatSEXP, SEXP w1matSEXP, SEXP w2matSEXP, SEXP maxiterSEXP, SEXP toleranceSEXP, SEXP initialSEXP, SEXP smallIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type noSignatures(noSignaturesSEXP);
    Rcpp::traits::input_parameter< std::string >::type distribution(distributionSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type pwr(pwrSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type wmat(wmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type hmat(hmatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w1mat(w1matSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w2mat(w2matSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< int >::type smallIter(smallIterSEXP);
    rcpp_result_gen = Rcpp::wrap(nmfall(data, noSignatures, distribution, method, alpha, pwr, wmat, hmat, w1mat, w2mat, maxiter, tolerance, initial, smallIter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nmfgenr_nmfall", (DL_FUNC) &_nmfgenr_nmfall, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_nmfgenr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
