# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nmfall <- function(data, noSignatures, distribution, method, alpha, pwr, wmat, hmat, w1mat, w2mat, maxiter = 10000L, tolerance = 1e-8, initial = 100L, smallIter = 500L) {
    .Call('_nmfgenr_nmfall', PACKAGE = 'nmfgenr', data, noSignatures, distribution, method, alpha, pwr, wmat, hmat, w1mat, w2mat, maxiter, tolerance, initial, smallIter)
}

